# Variables Team
TEAM_ID_ITC = '685846'
TEAM_ID     = 'DEDQBH6J8S'
TEAM_NAME   = 'SoftDesign Consultoria e Sistemas LTDA'

# Variables Access
APPLE_ID                   = 'juliano@julianoterres.com.br'
APPLE_PASSWORD_PUBLISH_APP = 'rdhy-qaju-wjtk-hyjz'

# Variables Project
PROJECT_IDENTIFIER      = 'br.com.softdesign.marveltests'
PROJECT_WORKSPACE       = 'Marvel.xcworkspace'
PROJECT_XCODEPROJ       = 'Marvel.xcodeproj'
PROJECT_PBXPROJ         = PROJECT_XCODEPROJ + '/project.pbxproj'
PROJECT_IPA_NAME        = 'marvel.ipa'
PROJECT_ICON_NAME       = 'AppIcon.png'
PROJECT_SCHEME          = 'Marvel'
PROJECT_SCHEME_UI_TESTS = 'MarvelUITests'
PROJECT_NAME            = 'SoftDesign Marvel'
PROJECT_LANGUAGES       = 'English'

# Variables Tests
TEST_DEVICES = ['iPhone 6s']

# Variables Screenshots
SCREENSHOTS_DEVICES = (["iPad Pro (12.9-inch)", "iPhone X", "iPhone 8 Plus"])

# Variables Rating
RATING_CONFIG_FILE_NAME = 'config.json'

# Variables Certificates
CERTIFICATE_PROVISION_PROFILE_NAME = 'marvel.mobileprovision'
CERTIFICATE_SIGNING_NAME           = 'iPhone Distribution: '+TEAM_NAME+' ('+TEAM_ID+')'

# Variables Paths
PATH_CERTIFICATES_PROVISION_PROFILE = './fastlane/certs/provisioning_profile/'
PATH_CERTIFICATES_SIGNING           = './fastlane/certs/signing/'
PATH_SCREENSHOTS                    = './fastlane/screenshots/'
PATH_METADATA                       = './fastlane/metadata/'
PATH_BUILD                          = './fastlane/builds/'
PATH_RATING                         = './fastlane/rating/'

# Variables Global Fastlane
ENV['FASTLANE_ITC_TEAM_ID']                         = TEAM_ID_ITC
ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD'] = APPLE_PASSWORD_PUBLISH_APP

# Start Fastlane

fastlane_version '2.99.0'
default_platform(:ios)

platform :ios do
  
  desc 'Run tests and swiftlint'
  lane :run_all_tests do
    swiftlint
    run_tests(
      workspace: PROJECT_WORKSPACE,
      devices: TEST_DEVICES,
      clean: true,
      scheme: PROJECT_SCHEME
    )
  end

  desc 'Run make screenshots'
  lane :run_screenshots do
    capture_ios_screenshots(
      scheme: PROJECT_SCHEME_UI_TESTS,
      devices: SCREENSHOTS_DEVICES,
      output_directory: PATH_SCREENSHOTS,
      output_simulator_logs: true,
      clear_previous_screenshots: true,
      skip_open_summary: true
    )
    frame_screenshots(
      white: true
    )
  end

  desc 'Run create a App ID in apple developer'
  lane :run_create_app_itunes do
    produce(
      username: APPLE_ID,
      itc_team_id: TEAM_ID_ITC,
      app_identifier: PROJECT_IDENTIFIER,
      app_name: PROJECT_NAME,
      language: PROJECT_LANGUAGES,
      team_name: TEAM_NAME
    )
  end

  desc 'Run certificates production'
  lane :run_get_certificates_production do
    get_certificates(
      development: false,
      username: APPLE_ID,
      output_path: PATH_CERTIFICATES_SIGNING,
      team_id: TEAM_ID
    )
  end
  
  desc 'Run provisioning profile production'
  lane :run_provisioning_profile_production do
    get_provisioning_profile(
      adhoc: false,
      force: true,
      app_identifier: PROJECT_IDENTIFIER,
      username: APPLE_ID,
      team_id: TEAM_ID,
      filename: CERTIFICATE_PROVISION_PROFILE_NAME,
      output_path: PATH_CERTIFICATES_PROVISION_PROFILE
    )
  end

  desc 'Run config provisioning profile'
  lane :run_config_provisioning_profile do
    backup_file(
      path: PROJECT_PBXPROJ
    )
    disable_automatic_code_signing(
      path: PROJECT_XCODEPROJ,
      use_automatic_signing: false
    )
    update_project_provisioning(
      xcodeproj: PROJECT_XCODEPROJ,
      profile: PATH_CERTIFICATES_PROVISION_PROFILE + CERTIFICATE_PROVISION_PROFILE_NAME,
      build_configuration: "Release",
      code_signing_identity: CERTIFICATE_SIGNING_NAME
    )
    update_project_provisioning(
      xcodeproj: PROJECT_XCODEPROJ,
      profile: PATH_CERTIFICATES_PROVISION_PROFILE + CERTIFICATE_PROVISION_PROFILE_NAME,
      build_configuration: "Debug",
      code_signing_identity: CERTIFICATE_SIGNING_NAME
    )
  end

  desc 'Run config provisioning profile automatic'
  lane :run_config_provisioning_profile_automatic do
    restore_file(
      path: PROJECT_PBXPROJ
    )
  end

  desc 'Run build and archive app'
  lane :run_build_app do
    run_config_provisioning_profile()
    build_app(
      scheme: PROJECT_SCHEME,
      workspace: PROJECT_WORKSPACE,
      include_bitcode: true,
      output_directory: PATH_BUILD,
      clean: true,
      export_method: 'app-store'
    )
    run_config_provisioning_profile_automatic()
  end

  desc 'Run upload app to itunes connect production'
  lane :run_send_store do
    upload_to_app_store(
      force: true,
      overwrite_screenshots: true,
      username: APPLE_ID,
      app_identifier: PROJECT_IDENTIFIER,
      metadata_path: PATH_METADATA,
      app_icon: PATH_METADATA + PROJECT_ICON_NAME,

  ipa: PATH_BUILD + PROJECT_IPA_NAME,
      app_rating_config_path: PATH_RATING + RATING_CONFIG_FILE_NAME,
      submit_for_review: true,
      automatic_release: true,
      skip_waiting_for_build_processing: true,
      # skip_binary_upload: true,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: true,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }
    )
  end

  desc 'Run upload app to itunes connect testfligth'
  lane :run_send_testfligth do
    upload_to_testflight(
      username: APPLE_ID,
      app_identifier: PROJECT_IDENTIFIER,
      ipa: PATH_BUILD + PROJECT_IPA_NAME,
      skip_waiting_for_build_processing: true,
      distribute_external: true,
      changelog: read_changelog
    )
  end

  desc 'Run all steps to upload app to itunes connect production'
  lane :send_production do
    run_all_tests
    run_screenshots
    run_get_certificates_production
    run_provisioning_profile_production
    run_build_app
    run_send_store
  end

  desc 'Run all steps to upload app to itunes connect testfligth'
  lane :send_testfligth do
    run_all_tests
    run_get_certificates_production
    run_provisioning_profile_production
    run_build_app
    run_send_testfligth
  end

end
